apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipsec
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ipsec
  template:
    metadata:
      labels:
        app: ipsec
    spec:
      containers:
      - image: xinb/ipsec:tagname
        name: ipsec
---
apiVersion: v1
kind: Service
metadata:
  name: ipsec
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:

  - name: "http-port-tcp"
    port: 500
  - name: "http-port-tcp2"
    port: 4500
    
  selector:
    app: ipsec
